# Generated by Django 3.0.8 on 2020-07-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200706_1521'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customers',
        ),
    ]
