# Generated by Django 3.0.4 on 2020-03-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='name',
        ),
    ]
