# Generated by Django 3.0.5 on 2020-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_img'),
        ),
    ]
