# Generated by Django 3.0.5 on 2020-06-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profile_img',
        ),
    ]
