# Generated by Django 3.0.5 on 2020-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20200609_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/image/default_profile.png', null=True, upload_to='Profile_img'),
        ),
    ]
