# Generated by Django 3.0.5 on 2020-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20200609_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_img'),
        ),
    ]
