# Generated by Django 3.0.7 on 2020-06-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_auto_20200609_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='fname',
        ),
    ]
