# Generated by Django 3.0.8 on 2020-07-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='tbl_orders',
        ),
    ]
