# Generated by Django 3.0.8 on 2020-07-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200707_1509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='tbl_products',
        ),
    ]
