# Generated by Django 3.0.4 on 2020-03-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200319_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
