# Generated by Django 3.0.4 on 2020-03-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200319_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=False, max_length=80),
        ),
    ]
