# Generated by Django 3.0.8 on 2020-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201110_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('', 'Choose Product Unit'), ('kg', 'kg'), ('l', 'litre'), ('pcs', 'pcs'), ('gm', 'gm'), ('m2', 'm2'), ('m3', 'm3'), ('ml', 'ml')], default='', max_length=50),
        ),
    ]
