# Generated by Django 3.0.4 on 2020-04-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
