# Generated by Django 3.0.7 on 2020-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('KILOGRAM', 'kg'), ('LITRE', 'l'), ('PACKET', 'pcs'), ('SQUAREMATER', 'm2'), ('CUBEMETER', 'm3'), ('MILLIMETRE', 'ml')], default='Choose Unit', max_length=50),
        ),
    ]
