# Generated by Django 3.0.7 on 2020-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UNIT', 'Choose Unit'), ('KILOGRAM', 'kg'), ('LITRE', 'l'), ('PACKET', 'pcs'), ('SQUAREMATER', 'm2'), ('CUBEMETER', 'm3'), ('MILLIMETRE', 'ml')], max_length=50),
        ),
    ]
