# Generated by Django 3.0.7 on 2020-06-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200630_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UNIT', 'Choose Product Unit'), ('Kg', 'kg'), ('L', 'litre'), ('Pcs', 'pcs'), ('m2', 'm2'), ('m3', 'm3'), ('ml', 'ml')], default='', max_length=50),
        ),
    ]
